[pytest]
DJANGO_SETTINGS_MODULE = stockmanagement.settings
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --cov=stockmanager --cov-report=term-missing
