# Generated by Django 5.2.3 on 2025-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0002_remove_stockitem_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
