# Generated by Django 5.2.3 on 2025-07-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0004_stock_alter_userholding_stock_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='userholding',
            name='stock',
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock_name',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userholding',
            name='symbol',
            field=models.CharField(default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userholding',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
