# Generated by Django 5.2.3 on 2025-07-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0005_remove_transaction_stock_remove_userholding_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userholding',
            name='quantity',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
