# Generated by Django 5.2.3 on 2025-07-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0006_alter_userholding_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userholding',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=1000.0),
        ),
    ]
